### ISSUE TITLE
HTTP 415 Client Error for createCollection

### ISSUE THREAD

**Issue by MHindermann** [Transkribus/TranskribusPyClient#10]
Hi, 

I'm getting a HTTP 415 Client Error when trying to create a new collection:
```
from TranskribusPyClient.client import TranskribusClient

client = TranskribusClient()
client.auth_login(sLogin="my@mail.com", sPwd="mypwd")
client.createCollection(sName="test_collection")
```
The exact error message is:
```
Traceback (most recent call last):
  File "myproject/main_TranskribusPyClient.py", line 5, in <module>
    client.createCollection(sName="test_collection")
  File "myproject\TranskribusPyClient\client.py", line 270, in createCollection
    resp.raise_for_status()
  File "myproject\venv\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 415 Client Error: 415 for url: https://transkribus.eu/TrpServer/rest/collections/createCollection
```

Any ideas? Thanks in advance.

**Comment by DRRV** [comment]
fixed
